### ISSUE TITLE
Write Technical Report

### ISSUE THREAD

**Issue by UTjkovar** [Sabriel567/cs373-idb#11]
**Requirements**
*  Write an initial technical report.
*  The audience comprises other software developers, as opposed to users.
*  For this phase make it at least 10 pages.
*  Document the RESTful API and the Flask models well.
*  Format the report clearly, attractively, and consistently, using good headers, figures, and grammar.

Section | Features
---------- | --------------
Title	| <ul><li>The group name</li> <li>Flask models</li></ul>
Introduction | <ul><li>What is the problem?</li> <li>What are the use cases?</li></ul>
Design | <ul><li>RESTful API Flask models</li></ul>
Tests | <ul><li>Unit tests of the Flask models</li></ul>
Other | <ul><li>Proof-read your report. Get another group to read it. </li> <li>Read it aloud. </li> <li>Create diagrams with captions. </li> <li>Create sections and subsections effectively.</li></ul>

**Comment by andythefan** [comment]
Here's a link: 

https://docs.google.com/document/d/1SB6DF6kur9gSdnH_7r-7ZRvFTLv0HXvVl9X0Fat9USM/edit?usp=sharing
