### ISSUE TITLE
Format search results from search endpoint on search.html

### ISSUE THREAD

**Issue by andythefan** [Sabriel567/cs373-idb#174]
- [ ] Displaying each of the pillars as separate results 
- [ ] Limiting number of results or paginating the rest

**Comment by UTjkovar** [comment]
Format Example:

/search/aquatics

AND
Athletes
     Charles Buchanan Hickcox
          Charles Buchanan Hickcox (United States) was in 100m backstroke (Aquatics) in Mexico 1968
     Ronald P. Mills
          Ronald P. Mills (United States) was in 100m backstroke (Aquatics) in Mexico 1968
     Roland Matthes
          Roland Matthes (East Germany) was in 100m backstroke (Aquatics) in Mexico 1968
Years
     1968
          Charles Buchanan Hickcox (United States) was in 100m backstrok (Aquatics) in Mexico 1968
          Ronald P. Mills (United States) was in 100m backstroke (Aquatics) in Mexico 1968
          Roland Matthes (East Germany) was in 100m backstroke (Aquatics) in Mexico 1968
Etc for other pillars

The explanations for each result comes from 'items_matched'
These explanation are only examples. So be creative and they don't need to be the same for each category
For numerous Athletes, Countries, etc. have a "Show More" drawer
For numerous blurbs for each result, have a "Show More" drawer
