### ISSUE TITLE
Debug Events Showing Both Seasons Issue

### ISSUE THREAD

**Issue by UTjkovar** [Sabriel567/cs373-idb#72]
Query for finding the season related to an event:
select distinct e.id, e.name, o.season from events e join medals m on m.event_id=e.id join olympics o on m.olympic_id=o.id order by e.name;

Query shows 2 entries for every event, with everything duplicated but the season.

 id  |                        name                        | season 
-----+----------------------------------------------------+--------
 201 | 10000m                                             | Summer
 201 | 10000m                                             | Winter
 206 | 10000m walk                                     | Summer
 206 | 10000m walk                                     | Winter

**Comment by Sabriel567** [comment]
Had some errors with data input that have now been fixed.
