### ISSUE TITLE
Potential Errors in Dataset/Population Error

### ISSUE THREAD

**Issue by UTjkovar** [Sabriel567/cs373-idb#73]
Running the following query results in multiple athletes getting Gold for the same event during the same olympics:

select * from medals; 

 id   |  rank  | athlete_id | event_id | country_id | olympic_id 
-------+--------+------------+----------+------------+------------
     1 | Gold   |        728 |      114 |         71 |         16
     2 | Gold   |        729 |      114 |        192 |         16
     3 | Gold   |       2092 |       79 |        192 |          1
     4 | Gold   |       2092 |       79 |        192 |         17
     5 | Silver |       3051 |       79 |        192 |          1
     6 | Silver |       3051 |       79 |        192 |         17
     7 | Gold   |       3052 |       79 |        192 |          1
     8 | Gold   |       3052 |       79 |        192 |         17

**Comment by Sabriel567** [comment]
I seems some if not all of these repeats indicate that the event was hosted for both men and women. We either need to store something of this effect in the events table, or do a join on the athletes table to get the gender of the athlete. Is there ever a case where men and women compete together?

**Comment by Sabriel567** [comment]
Put gender into the events table as well. Out put wasn't incorrect it just contained both male and female data
